### ISSUE TITLE
感谢开源！Vue 加载验证码期间和native表现形式不一致

### ISSUE THREAD

**Issue by OneSeven** [wenlng/go-captcha-vue#2]
Vue:
并且Vue在加载期间任然可以点击

![屏幕截图 2024-06-14 112316](https://github.com/wenlng/go-captcha-vue/assets/17974392/686ea829-007a-4af1-945a-5f1a5465ec06)

![屏幕截图 2024-06-14 113537](https://github.com/wenlng/go-captcha-vue/assets/17974392/81c47a8b-6aa2-4b20-8253-030c12572458)

Native

![屏幕截图 2024-06-14 112336](https://github.com/wenlng/go-captcha-vue/assets/17974392/4a3a9d34-46a1-4f47-80e8-77964a26b992)

**Comment by wenlng** [comment]
> Vue: 并且Vue在加载期间任然可以点击
> 
> ![屏幕截图 2024-06-14 112316](https://private-user-images.githubusercontent.com/17974392/339624388-686ea829-007a-4af1-945a-5f1a5465ec06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NDQ1MDgsIm5iZiI6MTcxODU0NDIwOCwicGF0aCI6Ii8xNzk3NDM5Mi8zMzk2MjQzODgtNjg2ZWE4MjktMDA3YS00YWYxLTk0NWEtNWYxYTU0NjVlYzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDEzMjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOWEwYWVhMzdhMGViMDZkMGZmMmRjMDMxODk4N2Y1ZjQ2Yzg1YmQ3YjQyYmJiODU2ZGY3ZThkNjY3ZWZhZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._YqORIMFDwOgJjUIM3DaYIvS6WMfXVK87zVnLKwJt9w)
> 
> ![屏幕截图 2024-06-14 113537](https://private-user-images.githubusercontent.com/17974392/339624949-81c47a8b-6aa2-4b20-8253-030c12572458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NDQ1MDgsIm5iZiI6MTcxODU0NDIwOCwicGF0aCI6Ii8xNzk3NDM5Mi8zMzk2MjQ5NDktODFjNDdhOGItNmFhMi00YjIwLTgyNTMtMDMwYzEyNTcyNDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDEzMjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNTZjNDk1ZjZmZjU5M2ZhYjAwNjRiNzc4MzI0NDY2NjczZDVhMjJlYzczZjhhOTkwYTI5NDU1N2I4MGM1OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PeRIHjC8JXIdmc65-CYVZdqebut0pDSdA8TRWgjgSwg)
> 
> Native
> 
> ![屏幕截图 2024-06-14 112336](https://private-user-images.githubusercontent.com/17974392/339624472-4a3a9d34-46a1-4f47-80e8-77964a26b992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NDQ1MDgsIm5iZiI6MTcxODU0NDIwOCwicGF0aCI6Ii8xNzk3NDM5Mi8zMzk2MjQ0NzItNGEzYTlkMzQtNDZhMS00ZjQ3LTgwZTgtNzc5NjRhMjZiOTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDEzMjMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYjA3NTg0MThhNjdjMzYyMzQ3ODAyNGFkZjQ1YmNiNWI5ODJkMjEwMTdhOTU1ZGIwNDQ2YmJhZjA2ZDk0ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mQ9XydwZsKnq3WH1gaDvVj0VCCFg23NzACxl0ZJ80Ck)

嘿嘿，你将图像渲染出来就好，在图像加载期间时是不允许点击的，只是 native 版本没有限制而已

**Comment by wenlng** [comment]
> 加载期间不允许点击是正常逻辑，vue没有做这个限制，vue版本加载期间如果图像为空，就图裂了，如果传“”，就加载效果也不显示了

“beta版本”应该会有，即将发布的“正式版本”是没有这个问题的

**Comment by wenlng** [comment]
正式版已发布，请使用正式版本
