### ISSUE TITLE
通过config修改title失败

### ISSUE THREAD

**Issue by Sway1023** [wenlng/go-captcha-vue#4]
安装go-captcha-vue3依赖后，发现引入gocaptcha-slide组件修改title不生效，尝试了一下源码的example，修改title是成功的。

**Comment by wenlng** [comment]
> 安装go-captcha-vue3依赖后，发现引入gocaptcha-slide组件修改title不生效，尝试了一下源码的example，修改title是成功的。

按照文档匹配一下依赖就好，vue2.7+ 的依赖是 go-captcha-vue@^1，vue3.0+的依赖是 go-captcha-vue@^2
