### ISSUE TITLE
props：data ref 响应式异常，文档未说明 slide confirm 事件的 clear 方法

### ISSUE THREAD

**Issue by LarryZhu-dev** [wenlng/go-captcha-vue#9]
如果不是看了下源码我可能一直不知道还需要调用 clear 方法，refresh 时 重设 x/y 值只有 y 生效了，x值只有调用 clear 时才会重置。

且实测 使用 ref 时组件不会动态响应，看了源码发现你的案例是 reactive ，试了一下确实是可以的，不知道是 vue 的问题还是怎么回事。

麻烦作者大大解答一下，最好能补充下文档。

**Comment by wenlng** [comment]
confirm 回调的第二个参数为 reset 方法，文档漏了写上
然后在 v2.0.3 版本已加了组件导出方法如  reset、clear 等，支持组件 ref 调用
https://github.com/wenlng/go-captcha-vue/tree/v2.0.3
